#include <iostream>

using namespace std;

enum class TokenType {
    // Keywords
    T_FUNCTION, T_INT, T_FLOAT, T_STRING, T_BOOL, T_CHAR, T_IF, T_ELSE, T_WHILE, T_RETURN, T_BREAK, 
    T_CONTINUE, T_PRINT, T_READ, T_TRUE, T_FALSE, T_NULL, T_VOID, T_INCLUDE, T_ELIF

    // Operators
    T_PLUS, T_MINUS, T_MULTIPLY, T_DIVIDE, T_MODULO, T_EQUAL, T_NOT_EQUAL, T_GREATER_THAN, T_LESS_THAN, 
    T_GREATER_THAN_EQUAL, T_LESS_THAN_EQUAL, T_AND, T_OR, T_NOT, T_ASSIGN, T_INCREMENT, T_DECREMENT, T_COMMA, 
    T_SEMICOLON, T_COLON, T_DOT, T_LPAREN, T_RPAREN, T_LBRACE, T_RBRACE, T_LBRACKET, T_RBRACKET, T_LBRACKET,

    // Punctuation
    T_PARENL, T_PARENR, T_BRACEL, T_BRACER, T_BRACKETL, T_BRACKETR,
    T_COMMA, T_SEMICOLON, T_COLON, T_DOT, T_QUOTES, 

    // Literals
    T_INT_LITERAL, T_FLOAT_LITERAL, T_STRING_LITERAL, T_CHAR_LITERAL, T_BOOL_LITERAL,

    // Identifiers
    T_IDENTIFIER, T_EOF, 

    // Error
    T_ERROR,
};
