#ifndef TOKEN_H
#define TOKEN_H

#include <string>

enum class TokenType {
    // Keywords (C/C++98/03)
    T_AUTO, T_BREAK, T_CASE, T_CHAR, T_CONST, T_CONTINUE, T_DEFAULT, T_DO,
    T_DOUBLE, T_ELSE, T_ENUM, T_EXTERN, T_FLOAT, T_FOR, T_GOTO, T_IF,
    T_INT, T_LONG, T_REGISTER, T_RETURN, T_SHORT, T_SIGNED, T_SIZEOF, T_STATIC,
    T_STRUCT, T_SWITCH, T_TYPEDEF, T_UNION, T_UNSIGNED, T_VOID, T_VOLATILE, T_WHILE,
    T_CLASS, T_PUBLIC, T_PRIVATE, T_PROTECTED, T_TEMPLATE, T_THIS, T_VIRTUAL,
    T_NEW, T_DELETE, T_TRY, T_CATCH, T_THROW, T_OPERATOR, T_FRIEND, T_INLINE,
    T_NAMESPACE, T_USING, T_ASM, T_BOOL, T_TRUE, T_FALSE, T_TYPEID, T_DYNAMIC_CAST,
    T_STATIC_CAST, T_REINTERPRET_CAST, T_CONST_CAST, T_EXPLICIT, T_MUTABLE,

    // Modern C++ Keywords (C++11 and newer)
    T_NULLPTR, T_CONSTEXPR, T_NOEXCEPT, T_DECLTYPE, T_STATIC_ASSERT, T_CHAR16_T,
    T_CHAR32_T, T_ALIGNAS, T_ALIGNOF, T_CO_AWAIT, T_CO_YIELD, T_CO_RETURN,
    T_CONCEPT, T_REQUIRES,

    // Literals
    T_IDENTIFIER, T_INTLIT, T_FLOATLIT, T_CHARLIT, T_STRINGLIT, T_BOOLLIT,
    
    // Operators
    T_PLUS, T_MINUS, T_ASTERISK, T_DIVIDE, T_MOD, T_INCREMENT, T_DECREMENT,
    T_ASSIGN, T_PLUS_ASSIGN, T_MINUS_ASSIGN, T_MULTIPLY_ASSIGN, T_DIVIDE_ASSIGN,
    T_MOD_ASSIGN, T_EQUAL, T_NOT_EQUAL, T_LESS, T_GREATER, T_LESS_EQUAL,
    T_GREATER_EQUAL, T_LOGICAL_AND, T_LOGICAL_OR, T_LOGICAL_NOT, T_AMPERSAND,
    T_BITWISE_OR, T_BITWISE_XOR, T_BITWISE_NOT, T_LEFT_SHIFT, T_RIGHT_SHIFT,
    T_LEFT_SHIFT_ASSIGN, T_RIGHT_SHIFT_ASSIGN, T_BITWISE_AND_ASSIGN,
    T_BITWISE_OR_ASSIGN, T_BITWISE_XOR_ASSIGN, T_ARROW, T_SCOPE,
    T_ARROW_ASTERISK, T_DOT_ASTERISK, T_SPACESHIP,

    // Punctuators
    T_SEMICOLON, T_LPAREN, T_RPAREN, T_LBRACE, T_RBRACE, T_LBRACKET, T_RBRACKET,
    T_COLON, T_COMMA, T_DOT, T_QUESTION, T_ELLIPSIS,

    // Preprocessor Directives
    T_HASH, T_INCLUDE, T_DEFINE, T_UNDEF, T_IFDEF, T_IFNDEF, T_ELIF,
    T_ENDIF, T_PRAGMA, T_LINE,
    
    // Special Tokens
    T_EOF, T_ERROR, T_COMMENT, T_WHITESPACE
};

struct Token {
    TokenType type;
    std::string value;
    int line;
    int column;

    Token(TokenType type, const std::string& v = "", int line = 1, int column = 1);
    std::string toString() const;
};

#endif // TOKEN_H